"""add info_updated_at, password_updated_at

Revision ID: 2d721a6ff893
Revises: 41b0a18a356f
Create Date: 2026-08-05 14:21:45.940777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d721a6ff893'
down_revision = '41b0a18a356f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_google_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.drop_column('profile_updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.create_unique_constraint(batch_op.f('users_google_id_key'), ['google_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('password_updated_at')
        batch_op.drop_column('info_updated_at')

    # ### end Alembic commands ###
