"""add info_updated_at, password_updated_at

Revision ID: 2d721a6ff893
Revises: 66982ff562fa
Create Date: 2026-08-05 14:21:45.940777

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2d721a6ff893"
down_revision = "66982ff562fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("users_google_id_key"),
            type_="unique",
        )
        batch_op.create_index(
            batch_op.f("ix_users_google_id"),
            ["google_id"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_google_id"))
        batch_op.create_unique_constraint(
            batch_op.f("users_google_id_key"),
            ["google_id"],
            postgresql_nulls_not_distinct=False,
        )

    # ### end Alembic commands ###
