"""Initial schema

Revision ID: 41b0a18a356f
Revises: 
Create Date: 2026-07-28 18:14:10.120158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b0a18a356f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_image_path', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profile_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('resource_spots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('material', sa.String(length=120), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=False),
    sa.Column('permission_note', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COLLECTED', name='resourcespotstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_spots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_spots_location_text'), ['location_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_spots_material'), ['material'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_spots_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_spots_status'), ['status'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('material', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location_text', sa.String(length=255), nullable=False),
    sa.Column('pickup_location_text', sa.String(length=255), nullable=True),
    sa.Column('trading_for_type', sa.Enum('SPECIFIC', 'NOTHING', 'NEGOTIATING', name='tradingfortype'), nullable=False),
    sa.Column('trading_for_value', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESERVED', 'COMPLETED', name='tradestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_location_text'), ['location_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('offerer_id', sa.String(length=36), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('material', sa.String(length=120), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='offerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['offerer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_offerer_id'), ['offerer_id'], unique=False)
        batch_op.create_index('ix_offers_one_pending_per_trade', ['trade_id'], unique=True, postgresql_where=sa.text("status = 'pending'"), sqlite_where=sa.text("status = 'pending'"))
        batch_op.create_index(batch_op.f('ix_offers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_trade_id'), ['trade_id'], unique=False)

    op.create_table('ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('rater_id', sa.String(length=36), nullable=False),
    sa.Column('rated_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_rating_score_range'),
    sa.ForeignKeyConstraint(['rated_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'rater_id', name='uq_rating_trade_rater')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_rated_id'), ['rated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_rater_id'), ['rater_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_trade_id'), ['trade_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('OFFER_RECEIVED', 'OFFER_ACCEPTED', 'OFFER_DECLINED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('related_trade_id', sa.String(length=36), nullable=True),
    sa.Column('related_offer_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['related_trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_trade_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_rater_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_rated_id'))

    op.drop_table('ratings')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_trade_id'))
        batch_op.drop_index(batch_op.f('ix_offers_status'))
        batch_op.drop_index('ix_offers_one_pending_per_trade', postgresql_where=sa.text("status = 'pending'"), sqlite_where=sa.text("status = 'pending'"))
        batch_op.drop_index(batch_op.f('ix_offers_offerer_id'))

    op.drop_table('offers')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.drop_index(batch_op.f('ix_trades_owner_id'))
        batch_op.drop_index(batch_op.f('ix_trades_location_text'))
        batch_op.drop_index(batch_op.f('ix_trades_category'))

    op.drop_table('trades')
    with op.batch_alter_table('resource_spots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_spots_status'))
        batch_op.drop_index(batch_op.f('ix_resource_spots_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_resource_spots_material'))
        batch_op.drop_index(batch_op.f('ix_resource_spots_location_text'))

    op.drop_table('resource_spots')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
