"""
check user schema

Revision ID: 66982ff562fa
Revises: 41b0a18a356f
Create Date: 2026-08-05 13:29:50.301447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66982ff562fa'
down_revision = '41b0a18a356f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('profile_updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('password_updated_at')
        batch_op.drop_column('info_updated_at')

    # ### end Alembic commands ###
